Better error reporting for browserify
When you get an error using browserify with the current config you get something akin to the following:

ParseError: Unexpected token .

this fix changes this to something more along the lines of 

/Users/reubendoetsch/recombine/orginal-labs/src/scripts/ng-app/services/recombine_api_service.js:15
      Restangular..setDefaultHttpFields({withCredentials: true});

which is massively helpful for debugging these sort of errors.

I checked other browserify errors and they all work as intended.